### ISSUE TITLE
tensorflow-addons not longer supported by tensorflow 2.6.0

### ISSUE THREAD

**Issue by riaqn** [google/automl#1071]
The code in this repo depends on TFA. 

See https://github.com/tensorflow/addons for compatibility matrix.

**Comment by qkum** [comment]
You are not helping much there.

The Documentation / Readme.txt in your link says it works. 

And you did not write what part of the code depends on TensorFlow/addons.

Wasting maybe hours of people's time for no reason just because you are lazy.

You already wasted at least 30 minutes of my time.

- If you are too lazy to write more than 2 lines of text - then don't write anything at all.

Thanks.

**Comment by riaqn** [comment]
@qkum This issue was closed days before you reply, and you are not a contributor of this repo. I don't understand how you came across this and decide to waste 30mins of your time. LOL.
