### ISSUE TITLE
DetDO vs YOLOv3

### ISSUE THREAD

**Issue by varghesealex90** [google/automl#169]
Hello All, 
When the paper claims DO to be faster than YOLOv3, is the post-processing (NMS) taken into consideration?

**Comment by mingxingtan** [comment]
Hi @varghesealex90 post-processing is not taken into account, since it highly depends on the implementation. In the current code of efficientdet, I simply copied the nms from [retinanet](https://github.com/tensorflow/tpu/tree/master/models/official/retinanet), but there are many fast nms implementations. Somme contributors have sent me emails that they are tring to add fast nms to this codebased. Hope we can see those soon.

We did not intend to compare the speed of YOLOv3 or MaskRCNN since we did not run it on the same machine, but I believe the flops and parameters are for network without nms.

**Comment by varghesealex90** [comment]
Thanks @mingxingtan
