### ISSUE TITLE
which version of tensorflow did this repo use?

### ISSUE THREAD

**Issue by Ringhu** [google/automl#219]

**Comment by BeautyMess** [comment]
TF1.15

**Comment by mingxingtan** [comment]
Please install the latest tensorflow 2.x

**Comment by sourabhyadav** [comment]
@mingxingtan  For me training and inference are working on TensorFlow 2.0.0a0. I did pull the code a week ago.
But I am facing 2 issues: 
a) ZERO mAP when trained with the custom dataset after training.
b) Not able to export the trained model.

Can both these issues be fixed with tensorflow 2.1? Shall I update the code to the latest?

**Comment by mingxingtan** [comment]
Yes, please pull the latest code and install the latest TF. Both issues should have been resolved.

**Comment by firefox1031** [comment]
@sourabhyadav , Did you solve the 2 issues you mentioned by installing tensorflow 2.1?

**Comment by sourabhyadav** [comment]
@firefox1031 Yes.
