### ISSUE TITLE
Detections much worse than YOLOv3?

### ISSUE THREAD

**Issue by AakashKumarNain** [google/automl#27]
I tried `EfficientDet-D0` to compare its performance with `Yolov3`but the results of `yolov3` are far superior than this one. 

## Results for ED-D0
![0](https://user-images.githubusercontent.com/11736571/77318674-74e2c600-6d33-11ea-98b5-27afb0db4481.jpg)

## Results for YOLOv3
![sample_0](https://user-images.githubusercontent.com/11736571/77318797-b1aebd00-6d33-11ea-928c-c6929bf9c48c.jpeg)

And here is the original image
![sample_img](https://user-images.githubusercontent.com/11736571/77320690-099af300-6d37-11ea-9d86-24f14dc2d540.png)

@mingxingtan is this expected?

**Comment by deepakcrk** [comment]
Please post original image also

**Comment by AakashKumarNain** [comment]
> Please post original image also

Done

**Comment by fsx950223** [comment]
Does these model trained on same dataset？
Yolov3 mark bus as ```truck```.
Efficientdet mark bus as ```bus```.

**Comment by AakashKumarNain** [comment]
Both are trained on `COCO` if I am right else how would you compare the performance as reported in the paper?

**Comment by fsx950223** [comment]
> Both are trained on `COCO` if I am right else how would you compare the performance as reported in the paper?

I try to train it on VOC2007 dataset and compare with my yolov3 model.

**Comment by WonTaeYeon** [comment]
Maybe..... In anchors.py' it is a good idea to increase MAX_DETECTIONS_PER_IMAGE (line 44) and decrease match_threshold (line 317; Default == 0.5).

**Comment by mingxingtan** [comment]
@AakashKumarNain This image is challenging: it has a lot of objects and many of them are very small. Therefore, you need to change the visualization settings in inferece.py line 208:  (1) change min_score_thresh=0.1   and (2) add max_boxes_to_draw=500.

After that you would get reasonable results.  However, since the original image is 1920x1080, much bigger than the default efficientdet-d0 size 512x512, you can simply change the image size of d0 by add "self.params['image_size'] = 1920" in inference.py line 234.

Here are the two updated results:

## EfficientDet-D0  (min_score_thresh=0.1 and max_boxes_to_draw=500, image_size=512)
![d0](https://user-images.githubusercontent.com/6027221/77340613-c61a9780-6cea-11ea-83a5-a243ab52cb66.jpg)

## EfficientDet-D0 (min_score_thresh=0.1 and max_boxes_to_draw=500, image_size=1920)
![d0-1920](https://user-images.githubusercontent.com/6027221/77340634-d16dc300-6cea-11ea-822c-63853f457329.jpg)

**Comment by AakashKumarNain** [comment]
@mingxingtan Thanks for clearing that up. The threshold for `yolov3` is much smaller, that makes sense. Thank you. 

Looking forward to the `lite` model. I basically want to replace all of my detector models to these, especially for edge devices

**Comment by mingxingtan** [comment]
@AakashKumarNain how's the copyright of this image?  I wonder may I use it in this repo? (like tutorial or README)

**Comment by AakashKumarNain** [comment]
@mingxingtan I took it from google images randomly.

**Comment by mingxingtan** [comment]
Gotcha. Do you still have the original link?

**Comment by AakashKumarNain** [comment]
Yes. It's [here.](https://www.google.com/search?q=traffic+scene+images&rlz=1C5CHFA_enIN879IN881&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiM1p_gmrHoAhWSb30KHXVBDF0Q_AUoAXoECAsQAw&biw=1344&bih=738#imgrc=Wo_saqv9S5tXgM)

**Comment by mingxingtan** [comment]
Great, thanks!

**Comment by AakashKumarNain** [comment]
You are welcome. 😄

**Comment by glenn-jocher** [comment]
YOLOv3 at 1920. Detection command is:

```bash
git clone https://github.com/ultralytics/yolov3
cd yolov3
python3 detect.py --img 608 --source img.jpg
```

![77320690-099af300-6d37-11ea-9d86-24f14dc2d540](https://user-images.githubusercontent.com/26833433/78506186-c4aa8f80-772c-11ea-97e5-5d797d74df49.png)

**Comment by HyunjiEllenPak** [comment]
> @AakashKumarNain This image is challenging: it has a lot of objects and many of them are very small. Therefore, you need to change the visualization settings in inferece.py line 208: (1) change min_score_thresh=0.1 and (2) add max_boxes_to_draw=500.
> 
> After that you would get reasonable results. However, since the original image is 1920x1080, much bigger than the default efficientdet-d0 size 512x512, you can simply change the image size of d0 by add "self.params['image_size'] = 1920" in inference.py line 234.
> 
> Here are the two updated results:
> 
> ## EfficientDet-D0 (min_score_thresh=0.1 and max_boxes_to_draw=500, image_size=512)
> ![d0](https://user-images.githubusercontent.com/6027221/77340613-c61a9780-6cea-11ea-83a5-a243ab52cb66.jpg)
> 
> ## EfficientDet-D0 (min_score_thresh=0.1 and max_boxes_to_draw=500, image_size=1920)
> ![d0-1920](https://user-images.githubusercontent.com/6027221/77340634-d16dc300-6cea-11ea-822c-63853f457329.jpg)

@mingxingtan 
Hi, I have a question about your above answer.
You said that the above image is hard image to detect objects, so we should decrease min_score_thresh=0.1 and increase add_max_boxes_to_draw=500. But I think that lowering the thresh to get the good result for hard images is not robust way because it makes getting over-detection results on easy images.

In the section 1.3 of your jupyter notebook tutorial,  your uploaded model efficientDet-d0 got good results even though setting min_score to 0.4.  Why our own trained model has poor result than your trained model? I guess most users has their own one GPU, So it has limitation to increase batch_size. But in your paper, you used lot of GPUs and batch size=128, that is generally impossible value to us. 
Are the EfficientDet result highly dependent on the batch size? How about your opinion?

**Comment by fsx950223** [comment]
> > @AakashKumarNain This image is challenging: it has a lot of objects and many of them are very small. Therefore, you need to change the visualization settings in inferece.py line 208: (1) change min_score_thresh=0.1 and (2) add max_boxes_to_draw=500.
> > After that you would get reasonable results. However, since the original image is 1920x1080, much bigger than the default efficientdet-d0 size 512x512, you can simply change the image size of d0 by add "self.params['image_size'] = 1920" in inference.py line 234.
> > Here are the two updated results:
> > ## EfficientDet-D0 (min_score_thresh=0.1 and max_boxes_to_draw=500, image_size=512)
> > ![d0](https://user-images.githubusercontent.com/6027221/77340613-c61a9780-6cea-11ea-83a5-a243ab52cb66.jpg)
> > ## EfficientDet-D0 (min_score_thresh=0.1 and max_boxes_to_draw=500, image_size=1920)
> > ![d0-1920](https://user-images.githubusercontent.com/6027221/77340634-d16dc300-6cea-11ea-822c-63853f457329.jpg)
> 
> @mingxingtan
> Hi, I have a question about your above answer.
> You said that the above image is hard image to detect objects, so we should decrease min_score_thresh=0.1 and increase add_max_boxes_to_draw=500. But I think that lowering the thresh to get the good result for hard images is not robust way because it makes getting over-detection results on easy images.
> 
> In the section 1.3 of your jupyter notebook tutorial, your uploaded model efficientDet-d0 got good results even though setting min_score to 0.4. Why our own trained model has poor result than your trained model? I guess most users has their own one GPU, So it has limitation to increase batch_size. But in your paper, you used lot of GPUs and batch size=128, that is generally impossible value to us.
> Are the EfficientDet result highly dependent on the batch size? How about your opinion?

I train and test voc2007 with efficientnet ckpt as backbone and I got 73 mAP.
Do you use efficientnet ckpt?
