### ISSUE TITLE
How to use the frozen pb model? What are output tensors to look for? How to use post processing?

### ISSUE THREAD

**Issue by sourabhyadav** [google/automl#302]
With the latest code I am able to generate _frozen.pb file. 

I am able to figure out the input tensor which works for me.
```
pred= sess.run('import/box_net/box-predict_4/BiasAdd:0',  {'import/input:0': raw_images})
```

**Question:**
1: ```pred``` is the shape of (1, 4, 4, 36). How to interpret these results?
2: What are the other output nodes I have to look for?
3: How to run post-processing for the predicted results?  

A code snippet could be helpful to predict the using frozen pb model.

**Comment by mingxingtan** [comment]
I added instructions in README, but basically you can run:

!python model_inspect.py --runmode=saved_model_infer \
  --model_name=efficientdet-d0   --ckpt_path=efficientdet-d0 \
  --input_image_size=1920x1280  \
  --saved_model_dir=/tmp/saved_model/efficientdet-d0_frozen.pb  \
  --input_image=img.png --output_image_dir=/tmp/

This is almost the same as inferencing with saved model, but you just pass a frozen_graph file instead of a folder name to saved_model_dir.  (Certainly, it is not a good practice to use the same flag to do different things, but this is just a demo, and we don't recommend frozen graph in general).

**Comment by stuurgurs** [comment]
@mingxingtan You avoided answering. I don't have the option of not using a frozen graph. I would like to understand how to interpret the result. Size of my output tensor is [1,18,7,7]  
@sourabhyadav were you able to find out the answers to your questions?
