### ISSUE TITLE
What is the exact difference between training with --ckpt_path=efficientdet-d0 and --backbone_ckpt=efficientnet-b0 ?

### ISSUE THREAD

**Issue by fitoule** [google/automl#345]
Both are transfer learning from pre trained model on coco. 
I tested both. On my custom dataset --ckpt_path=efficientdet-d0 is better, but i would know the difference ?
In wich case you should advice to use one or the other ?

**Comment by mingxingtan** [comment]
A detection model has three components:  (1) backbone; (2) FPN; (3) HEAD (or class/box prediction network).

If you use --backbone_ckpt=efficientnet-b0, then the backbone is initialized with ImageNet pretrained weights, while FPN and HEAD are randomly initialized.

If you use --ckpt_path=efficientdet-d0, then all backbone, FPN, and HEAD are initialized with COCO-pretrained weights.

In general, if you are doing transfer learning,  it is recommended to use --ckpt_path=efficientdet-d0 since it will initialize all backbone/FPN/HEAD.
