### ISSUE TITLE
ValueError: Variable efficientnet-b6/stem/conv2d/kernel already exists, disallowed

### ISSUE THREAD

**Issue by deepakcrk** [google/automl#41]
While looping through images like this:

```
driver = inference.InferenceDriver(MODEL, ckpt_path, image_size=image_size)
for m in imag_list:
    driver.inference(m,
             img_out_dir,
             min_score_thresh=min_score_thresh,
             max_boxes_to_draw=max_boxes_to_draw,
             line_thickness=line_thickness)
```

I am getting following error:

`    ValueError: Variable efficientnet-b6/stem/conv2d/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope?`

**Comment by mingxingtan** [comment]
Hi @deepakcrk, this is because the driver.inference will construct a graph each time it is called. To help mitigate your problem, I have provided another utility here:

https://github.com/google/automl/blob/7768c499ede4a732fde022a24d8525b3396b50a4/efficientdet/inference.py#L240

In this utility, the graph is constructed once, and you can repeated run inference for different images.

**Comment by mingxingtan** [comment]
Here is a code example:

```
    driver = inference.ServingDriver('efficientdet-d0', '/tmp/efficientdet-d0')
    driver.build()
    for f in tf.io.gfile.glob('/tmp/*.jpg'):
      image = Image.open(f)
      predictions = driver.serve(image)
      out_image = driver.visualize(image, predictions[0])
```
