### ISSUE TITLE
No FPS improvement when doing batch inference

### ISSUE THREAD

**Issue by davidmurray** [google/automl#476]
Hi,

I am using this detection model. It works quite well! Because I don't have a graphics card, I run all of this on my CPU.

Right now, with the `d0` model, I get about `3.7 FPS` on my CPU when doing single image inference (batch size 1).

However, when doing batch size 8 or 16 or even 32, the FPS throughput does not increase. It still hovers around `3.7 FPS`. I have re-exported a new SavedModel for each of these batch sizes.

Note that I have enough RAM for all of these images to be in memory.

Is batch inference supposed to improve the inference speed on CPU and GPU, or only GPU?

Thanks,
David

**Comment by mingxingtan** [comment]
Hi @davidmurray , batch inference is supposed to improve throughput for GPU/TPU, because if batch size is 1, then these accelerators are usually underutilized. For example, if you run the colab with T4 GPU, you should be able to see higher throughput with batch size 4 or 8.

CPU has limited parallism, so higher batch size my not help much for single CPUs.  But if you have a server CPU with many CPU cores, it may still help.

**Comment by davidmurray** [comment]
Hi @mingxingtan! Thanks for the answer, it helps me understand what is going on.

I have noticed that when doing single image inference, this model is using all 8 cores of my laptop i7 CPU at the same time. Is that normal? Wouldn't using just a single core let us do parallelism on an 8-core CPU?

**Comment by mingxingtan** [comment]
@davidmurray 

yes, TF always tries to use all cores to run each op. It is possible to improve throughput by tuning inter_op_parallelism_threads and intra_op_parallelism_threads, see: https://stackoverflow.com/questions/41233635/meaning-of-inter-op-parallelism-threads-and-intra-op-parallelism-threads
