### ISSUE TITLE
BFlops is not the same as the results reported in the paper.

### ISSUE THREAD

**Issue by LiangTinting** [google/automl#51]
Hi there! Excellent work and thank you for sharing the code!
I have a question about BFlops calculation. I used the efficientdet/model_inspect.py to compute the Efficientdet-D5 flops and got 270.77BFlops, which is about twice the 135 BFlops reported in paper.
Our results,
![image](https://user-images.githubusercontent.com/18143311/77608148-5826d800-6f57-11ea-8c75-d0699882c090.png)
Reported in [EfficientDet](https://arxiv.org/pdf/1911.09070.pdf)
![截屏2020-03-26下午12 04 29](https://user-images.githubusercontent.com/18143311/77609110-0fbce980-6f5a-11ea-98cf-ad6c0a8c6fe6.png)

What's more,  I noticed that with a unified unit (BFlops), the number of Flops of NAS-FPN is also half of that reported in your paper. 
Reported in [NAS-FPN](https://arxiv.org/pdf/1904.07392.pdf),
![2031585191959_ pic](https://user-images.githubusercontent.com/18143311/77608483-4e51a480-6f58-11ea-920a-42233b15af66.jpg)
Reported in [EfficientDet](https://arxiv.org/pdf/1911.09070.pdf),
![1585195071970](https://user-images.githubusercontent.com/18143311/77608744-0ed78800-6f59-11ea-9a07-dd1718a4f761.jpg)
It would be great if you could solve my confusion. Thanks a lot!

**Comment by mingxingtan** [comment]
Hi @LiangTinting , you are right the reported FLOPS in the code is about twice larger than the paper.

This is because the EfficientDet paper uses FLOPS to denote "number of multiply-adds" (see page 1 footnote), where each "multiply-add" is counted as 2 ops in the code.  However, in the NAS-FPN paper, FLOPs denotes number of operations, same as the code.

I had a hard time to pick which way to go, but somehow we decided to use FLOPs to denote "number of multiple-adds", following the convention of many previous work.

Sorry for the confusion, but I hope it answers your question.

**Comment by mingxingtan** [comment]
I am going to close this issue, but feel free to reopen it or add more comments. Thanks!
