### ISSUE TITLE
Different Number of Aspect Ratios

### ISSUE THREAD

**Issue by mm7721** [google/automl#593]
Is it possible to increase the number of box aspect ratios?  The default is 3: [(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)], and I'd like to increase it to something like: [(1.0, 1.0), (1.4, 0.7), (0.7, 1.4), (1.6, 0.6)]...but this gives an error:

ValueError: Shape of variable box_net/box-predict/bias:0 ((144,)) doesn't match with shape of tensor box_net/box-predict/bias ([36]) from checkpoint reader.

So I'm guessing some other params need to be updated too, but it's not immediately obvious which ones.

Thanks.

**Comment by mingxingtan** [comment]
This is expected: because you changed the aspect_ratios, the model needs to output more anchor predictions, causing variable mismatch.

I realized that the original var_exclude_expr is too complicated, so just added a simpler option "skip_mismatch" (true in default). With this option, it would automatically skip loading variables if shape mismatch.

If you check out the latest code and rerun your command (changing aspect_ratios), it should succeed.

**Comment by mm7721** [comment]
@mingxingtan, thanks for the update.  Quick question: with skip_mismatch, will it simply ignore my custom aspect_ratios?  Or will it load them and find a way to adjust the model?

**Comment by mingxingtan** [comment]
It will use your custom aspect ratios, but it would skip loading pretrained variables if their shape doesn't match (meaning those variables will be initialized randomly)
