### ISSUE TITLE
Clarification on arbitrary input image size

### ISSUE THREAD

**Issue by zishanahmed08** [google/automl#638]
the tutorial states that we can set input image size to any desired value .however the paper states as below
**d) Input image resolution: Since the feature levels 3–7 are used in BiFPN, the input resolution must be divisible by 2⁷ = 128, so the resolution of the image is linearly increased using equation (3).**

![image](https://user-images.githubusercontent.com/28828606/88925022-49895e00-d274-11ea-8d69-4fe312e82ba2.png)

So how is this managed? is the arbitrary input size provided by use resized to default size?

**Comment by InfiniteLife** [comment]
You can train network on any size you like, although I've noticed that non-square resolution in such case produces artifacts. During the network conversion for inference you must specify your arbitrary input size which will be used for inference since resizing operation is embedded in network graph I believe.

**Comment by mingxingtan** [comment]
Hi @zishanahmed08   the resolution scaling rule is for better efficiency, but you can train and network with any resolution and run inference in any resolution. This is because convolutional network weights are independent to image size (thanks to the "convolutional" operations).

Again, the scaling rules are mostly for COCO, and you may need different training image sizes for other datasets.
