### ISSUE TITLE
Question about augmentation pipeline in InputReader

### ISSUE THREAD

**Issue by InfiniteLife** [google/automl#694]
I am trying to implement some custom augmentations and kind of confused about it. 
1. Why is there 
```
  @tf.autograph.experimental.do_not_convert
  def dataset_parser(self, value, example_decoder, anchor_labeler, params):
```
do_not_convert - why it is explicitly specified? I tried to comment it and it works without it too.

2. Can I just place my numpy function inside `dataset_parset` and expect that AutoGraph will convert it? 
I tried to place functions like `print()`, `sys.stderr.write()`, `openfile('file.txt', 'w')` inside the body but they get executed only 1 time and I get no warnings or errors from AutoGraph. 

How I can understand that my custom function actually gets executed? 

As I understand I also can write them using tf function or `tf.py_function` but I also do not understand if there is guarantee this code will be executed

Will be happy for any hints how this actually works inside tensorflow framework

**Comment by kartik4949** [comment]
@InfiniteLife Hi,
1.If you look closely to dataset_parser method , there are lot of if statements consisting augmentations 
which  will not work if wrapped with autograph/static graph , hence for generic , they made autograph.do_not_convert because conversion for some augmentation might not work , you try it out by keeping let say autoaugment true and removing that decorator .

 2.print will not work inside autograph  try with tf.print , keeping numpy code inside autograph means you want to do eager execution which is not possible if you are making it static graph,hence you cant use numpy code

3.you can debug your function normally if not a autograph function.
Thanks

**Comment by mingxingtan** [comment]
Hi @InfiniteLife, tf.autograph.experimental.do_not_convert is added by @fsx950223 , and I believe it is just optional (you can safely remove it if needed).

Wrapping your customized preprocessing with tf.py_function is a good idea. If the output is the input of another tensorflow op, then it has to be executed. To verify this, you can add print statement in py_function (or tf.Print for tf ops)

**Comment by InfiniteLife** [comment]
@kartik4949 @mingxingtan thank you, that makes more sense now. I will try to implement some simple functions with tensorflow and wrap some geometric stuff in py_function.

**Comment by kartik4949** [comment]
Thanks @InfiniteLife Im closing the Issue ,reopen if you need further help.
