### ISSUE TITLE
[help] what is the 'training_file_pattern'? 

### ISSUE THREAD

**Issue by WonTaeYeon** [google/automl#8]
hi, thx for your code 

How should I input training data in local computer?

**Comment by KaqiKaqi** [comment]
For example, in directory /Path/to/coco, you have the following tfrecord files:
coco_train.record-00000-of-00100
coco_train.record-00001-of-00100
coco_train.record-00002-of-00100
coco_train.record-00003-of-00100
coco_train.record-00004-of-00100
coco_train.record-00005-of-00100
coco_train.record-00006-of-00100
coco_train.record-00007-of-00100
coco_train.record-00008-of-00100
coco_train.record-00009-of-00100

You can pass "/Path/to/coco/coco_train*" as training_file_pattern.

**Comment by xafarranxera** [comment]
And what about the same for testing? How can I get predictions for a bunch of images at the same time?

Thanks.

**Comment by mingxingtan** [comment]
There was a small bug in inference.py, and I have fixed that in 856d659

I have verified the following commands run well:

$ python model_inspect.py --model_name=efficientdet-d0 --ckpt_path=/tmp/efficientdet/efficientdet-d0/ --runmode=infer --input_image=/tmp/effin/*.jpg --output_image_dir=/tmp/effout

I would close this bug now, but feel free to reopen it if you still have issues.

Since this issue is similar to https://github.com/google/automl/issues/6, I am going to close this issue, but please feel free to reopen it if you still have this issue.
