### ISSUE TITLE
Paper Question, Resolution input in D7

### ISSUE THREAD

**Issue by dimimal** [google/automl#912]
In the paper you describe that you used equation 3 to produce the proper resolution. However, this gives a result of 1408 for D7 instead of 1536 you describe in your results. Am I missing anything here?

**Comment by mingxingtan** [comment]
Hi @dimimal

Since this is the last model, I just wanted to push the accuracy. I chose 1536 because it was the largest image size that could fit batch size 4 for a single TPU core.

BTW, the image size scaling rule is highly heuristic; you are free to make your own tweaks based on your own datasets (especially for image size).
