### ISSUE TITLE
Output of only_network exported model?

### ISSUE THREAD

**Issue by cnmckee** [google/automl#970]
Hello,
I have exported my trained model using the "only_network" flag, but am very confused about the outputs. I assumed the outputs would be similar to the full network outputs, ie. [class_outputs, box_outputs], since only_network means you're simply exporting the EfficientDetNet object without any post-processing. However, these are the outputs generated by the SavedModel:
![image](https://user-images.githubusercontent.com/43614259/112684368-8ecc5280-8e38-11eb-9863-6cba892f0cc7.png)
Can you please explain what these outputs of various square shapes are and how to get the non-post-processed class and box outputs? 
Thanks.

**Comment by cnmckee** [comment]
@mingxingtan Any help here would be very much appreciated

**Comment by hoangmt** [comment]
I am interested in this also. How from this output we can get back normal output?

**Comment by mingxingtan** [comment]
Hi @cnmckee  and @hoangmt 

You are right, the outputs are simple a concat of [class_outputs, box_outputs]. However, since we are using multi-scale features, they actually look like this:

class_outputs: [output0, output1, output2, output3, output4], where output0 has resolution 64x64 and output4 has resolution 4x4.
box_outputs:  [output5, output6, output7, output8, output9], where output5 has resolution 64x64 and output9 has resolution 4x4.

If you want a flatten [class_outputs, box_outputs], you can do something like this: https://source.corp.google.com/piper///depot/google3/third_party/brain_automl/efficientdet/keras/postprocess.py;rcl=372842164;l=65
