### ISSUE TITLE
Can this model return correct AP and mAP value?

### ISSUE THREAD

**Issue by jiansfoggy** [google/automl#973]
Hi, did you get normal AP when you run this model?
I use this model to train coco2017. But I get -1 AP, when I evaluated the model from both training and validation dataset.

Here is how I run the code
CUDA_VISIBLE_DEVICES=1,2 python3 main.py --mode=train_and_eval  \
    --train_file_pattern=tfrecord/train* \
    --val_file_pattern=tfrecord/val*  \
    --model_name=efficientdet-d0  \
    --model_dir=./tmp/efficientdet-d0-finetune  \
    --eval_after_train=True \
    --ckpt=efficientdet-d0 \
    --train_batch_size=32 \
    --eval_batch_size=32 --eval_samples=5088 \
    --num_examples_per_epoch=1024 --num_epochs=20  \
    --strategy=gpus

Here is the screenshot.
<img width="1102" alt="Screen Shot 2021-03-28 at 4 51 47 PM" src="https://user-images.githubusercontent.com/17891213/113604369-698ecf80-9602-11eb-8a77-4be9325b703b.png">

Now, I am wondering if I use the wrong command to run the model?

**Comment by fsx950223** [comment]
You should specific val_json_file by ```--val_json_file```

**Comment by jiansfoggy** [comment]
> You should specific val_json_file by `--val_json_file`

Thank you. Let me have a try.

**Comment by ameyparanjape** [comment]
Even with all the correct `hyperparameters` and `input filenames`, there is still possibility of getting `-1` as some AP/AR scores, since `APs, APm, APl, ARs, ARm and ARl` depend on [area threshold](https://cocodataset.org/#detection-eval), so if your dataset does not have bbox within any of the `small, medium, large` categories (since the denominator in the precision calculation is 0, it gives out -1 to avoid division by 0)
I would suggest analyzing the data and range of areas of the bbox to get more insights on this

**Comment by Cavan09** [comment]
> > You should specific val_json_file by `--val_json_file`
> 
> Thank you. Let me have a try.

Did you end up getting this to work with a JSON file defined? I tried but I'm getting errors now from pycocotools now

**Comment by BhandarkarPawan** [comment]
@jiansfoggy 
did you solve this issue? I am having the same problem right now...
